### ISSUE TITLE
@ - raise the a inside the loop please! all styles

### ISSUE THREAD

**Issue by EbenSorkin** [aoifemooney/cutivemono#6]
The bottom might also be less long and or be more open.

**Comment by aoifemooney** [comment]
I agree with the bottom being more open, but when I looked at all 4 styles, the a seemed correctly optically positioned top to bottom but more to the right than in the center, so I moved all to the left, and I also moved the at down on the body so that it aligned with the x height more, it was somewhere between the cap and the lowercase in terms of any alignment, so I think this feels more comfortable and grounds better on the line. I also tidied up some curve issues here. I'm going to go through and tidy up curve timing as a separate issue. There are a lot of awkward timing issues in the curves, glad you pointed out the @ as it drew my attention to them. =)
